version: "3.8"

services:
  backend:
    build: ./orchestration-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"

  frontend:
    build: ./orchestration-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

